spring:
  application:
    name: admin-management

keycloak:
  server-url: http://localhost:9080
  realm: admin-management-system
  client-id: admin-management-client
  client-secret: MD6oJLRRGVbpxDEKB2kolNkXvkChrrvn

server:
  port: 8085