spring:
  application:
    name: admin-management
  datasource:
    url: ${DB_URL:jdbc:h2:mem:admin_management_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}


server:
  port: 8085